services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - featstack

  api:
    image: ghcr.io/${GH_USERNAME}/api:${API_VERSION}
    restart: unless-stopped
    expose:
      - '3000'
    env_file:
      - .env
    depends_on:
      - postgres
    command: >
      sh -c "
        npx prisma migrate deploy --schema=./libs/shared/auth/infrastructure/src/lib/prisma &&
        node dist/main.js
      "
    networks:
      - featstack

  web-app:
    image: ghcr.io/${GH_USERNAME}/web-app:${WEB_APP_VERSION}
    restart: unless-stopped
    expose:
      - '80'
    depends_on:
      - api
    networks:
      - featstack

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - web-app
      - api
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - featstack

volumes:
  postgres_data:

networks:
  featstack:
    driver: bridge
